const simpleDB = require("./components/simpleDB")

//simpleDB.read('database.db')
//simpleDB.write('database.db', "testtt", [JSON.stringify({Name:"jens",Age:"12"})])
//simpleDB.createDB('epic')
//simpleDB.deleteTable('database.db', "cool")
//simpleDB.readTableWhere('database.db', "dsa")
//simpleDB.readRowWhere('database.db', 'Name')
//simpleDB.updateTable('database.db', 'epic', "123", [JSON.stringify({Name:"alfred",Age:"212"})])
simpleDB.deleteRows('database.db', 'Name')
